/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/email-change/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm Email Change Endpoint */
        post: operations["confirmEmailChange"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/invitations/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept Invitation Endpoint */
        post: operations["acceptInvitation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/invitations/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Preview Invitation Endpoint */
        get: operations["previewInvitation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login Endpoint */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout Endpoint */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout All Endpoint */
        post: operations["logoutAll"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password-reset/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Password Reset Confirm Endpoint */
        post: operations["passwordResetConfirm"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password-reset/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Password Reset Request Endpoint */
        post: operations["passwordResetRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register Endpoint */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/resend-verification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resend Verification Endpoint */
        post: operations["resendVerification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/verify-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify Email Endpoint */
        post: operations["verifyEmail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/contact": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Contact Endpoint */
        post: operations["submitContact"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Me Endpoint */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Me Endpoint */
        patch: operations["updateMe"];
        trace?: never;
    };
    "/api/v1/me/email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request Email Change Endpoint */
        post: operations["requestEmailChange"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/invitations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List My Invitations Endpoint */
        get: operations["listMyInvitations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change Password Endpoint */
        post: operations["changePassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List My Sessions Endpoint */
        get: operations["listMySessions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke My Session Endpoint */
        delete: operations["revokeMySession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orgs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List My Organizations Endpoint */
        get: operations["listMyOrganizations"];
        put?: never;
        /** Create Organization Endpoint */
        post: operations["createOrganization"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orgs/{org_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Organization Endpoint */
        get: operations["getOrganization"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orgs/{org_id}/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Audit Endpoint */
        get: operations["listAudit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orgs/{org_id}/audit/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Audit Endpoint */
        get: operations["exportAudit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orgs/{org_id}/imports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Imports Endpoint */
        get: operations["listImports"];
        put?: never;
        /** Create Import Endpoint */
        post: operations["createImport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orgs/{org_id}/imports/{batch_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Import Endpoint */
        get: operations["getImport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orgs/{org_id}/imports/{batch_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Import Endpoint */
        post: operations["cancelImport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orgs/{org_id}/imports/{batch_id}/commit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Commit Import Endpoint */
        post: operations["commitImport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orgs/{org_id}/imports/{batch_id}/issues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Import Issues Endpoint */
        get: operations["listImportIssues"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orgs/{org_id}/imports/{batch_id}/issues/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Import Issues Endpoint */
        get: operations["exportImportIssues"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orgs/{org_id}/imports/{batch_id}/mapping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Apply Mapping Endpoint */
        put: operations["applyMapping"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orgs/{org_id}/imports/{batch_id}/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Preview Import Endpoint */
        get: operations["previewImport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orgs/{org_id}/imports/{batch_id}/uploaded": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm Upload Endpoint */
        post: operations["confirmUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orgs/{org_id}/imports/{batch_id}/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate Import Endpoint */
        post: operations["validateImport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orgs/{org_id}/invitations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Invitations Endpoint */
        get: operations["listInvitations"];
        put?: never;
        /** Create Invitation Endpoint */
        post: operations["createInvitation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orgs/{org_id}/invitations/{invitation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke Invitation Endpoint */
        delete: operations["revokeInvitation"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orgs/{org_id}/invitations/{invitation_id}/resend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resend Invitation Endpoint */
        post: operations["resendInvitation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orgs/{org_id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Members Endpoint */
        get: operations["listMembers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orgs/{org_id}/members/transfer-ownership": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Transfer Ownership Endpoint */
        post: operations["transferOwnership"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orgs/{org_id}/members/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Member Endpoint */
        delete: operations["removeMember"];
        options?: never;
        head?: never;
        /** Change Member Role Endpoint */
        patch: operations["changeMemberRole"];
        trace?: never;
    };
    "/api/v1/orgs/{org_id}/rework": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Candidates Endpoint */
        get: operations["listCandidates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orgs/{org_id}/rework/{candidate_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Candidate Endpoint */
        get: operations["getCandidate"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orgs/{org_id}/rework/{candidate_id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Review Endpoint */
        post: operations["createReview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orgs/{org_id}/rework/{candidate_id}/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Review History Endpoint */
        get: operations["listReviewHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orgs/{org_id}/settings/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Review Categories Endpoint */
        get: operations["listReviewCategories"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orgs/{org_id}/settings/root-causes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Root Causes Endpoint */
        get: operations["listRootCauses"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AcceptInvitationRequest */
        AcceptInvitationRequest: {
            /** Token */
            token: string;
        };
        /**
         * ActorType
         * @enum {string}
         */
        ActorType: "user" | "system" | "api_key";
        /** AuditEventOut */
        AuditEventOut: {
            /** Action */
            action: string;
            /** Actor Label */
            actor_label: string;
            actor_type: components["schemas"]["ActorType"];
            /** Actor User Id */
            actor_user_id: string | null;
            /** Changes */
            changes: {
                [key: string]: unknown;
            } | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Request Id */
            request_id: string | null;
            /** Resource Id */
            resource_id: string | null;
            /** Resource Type */
            resource_type: string | null;
            /** Summary */
            summary: string;
        };
        /** AuditListOut */
        AuditListOut: {
            /** Data */
            data: components["schemas"]["AuditEventOut"][];
            page: components["schemas"]["AuditPageOut"];
        };
        /** AuditPageOut */
        AuditPageOut: {
            /** Has More */
            has_more: boolean;
            /** Limit */
            limit: number;
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** BooleanTransform */
        BooleanTransform: {
            /** True Values */
            true_values?: string[] | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "boolean";
        };
        /** CandidateCustomerOut */
        CandidateCustomerOut: {
            /** Account Number */
            account_number: string | null;
            /** Display Name */
            display_name: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
        };
        /** CandidateDetailOut */
        CandidateDetailOut: {
            band: components["schemas"]["ScoreBand"];
            current_review: components["schemas"]["ReworkReviewOut"] | null;
            customer: components["schemas"]["CandidateCustomerOut"] | null;
            /** Days Between */
            days_between: number;
            /**
             * Detected At
             * Format: date-time
             */
            detected_at: string;
            equipment: components["schemas"]["CandidateEquipmentOut"] | null;
            followup_job: components["schemas"]["CandidateJobOut"];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Suppressed */
            is_suppressed: boolean;
            prior_job: components["schemas"]["CandidateJobOut"];
            /** Score */
            score: string;
            /** Signals */
            signals: components["schemas"]["CandidateSignalOut"][];
            /** Suppressed By Signal Key */
            suppressed_by_signal_key: string | null;
            suppression_reason: components["schemas"]["CandidateSuppressionReason"] | null;
            /** Top Signals */
            top_signals: components["schemas"]["CandidateSignalOut"][];
            workflow_status: components["schemas"]["CandidateWorkflowStatus"];
        };
        /** CandidateEquipmentOut */
        CandidateEquipmentOut: {
            /** Asset Tag */
            asset_tag: string | null;
            /** Equipment Type */
            equipment_type: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Manufacturer */
            manufacturer: string | null;
            /** Model */
            model: string | null;
            /** Serial Number */
            serial_number: string | null;
        };
        /** CandidateJobOut */
        CandidateJobOut: {
            /** Completed At */
            completed_at: string | null;
            /** Currency Code */
            currency_code: string;
            /** Customer Id */
            customer_id: string | null;
            /** Description */
            description: string | null;
            /** Diagnosis Text */
            diagnosis_text: string | null;
            /** Equipment Id */
            equipment_id: string | null;
            /** External Id */
            external_id: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Invoice Number */
            invoice_number: string | null;
            /** Is No Charge */
            is_no_charge: boolean;
            /** Is Warranty */
            is_warranty: boolean;
            /** Job Number */
            job_number: string | null;
            /** Labor Amount */
            labor_amount: string | null;
            /** Location Id */
            location_id: string | null;
            /** Parts Amount */
            parts_amount: string | null;
            /** Raw Job Type */
            raw_job_type: string | null;
            /** Raw Service Category */
            raw_service_category: string | null;
            /** Resolution Text */
            resolution_text: string | null;
            /** Revenue Amount */
            revenue_amount: string | null;
            /** Scheduled At */
            scheduled_at: string | null;
            /**
             * Service Date
             * Format: date
             */
            service_date: string;
            /** Started At */
            started_at: string | null;
            status: components["schemas"]["JobStatus"];
            /** Summary */
            summary: string | null;
            /** Symptoms Text */
            symptoms_text: string | null;
            /** Technician Id */
            technician_id: string | null;
            /** Technician Name */
            technician_name: string | null;
            /** Warranty Reference */
            warranty_reference: string | null;
        };
        /** CandidateListOut */
        CandidateListOut: {
            /** Data */
            data: components["schemas"]["CandidateSummaryOut"][];
            page: components["schemas"]["CandidatePageOut"];
        };
        /** CandidatePageOut */
        CandidatePageOut: {
            /** Has More */
            has_more: boolean;
            /** Limit */
            limit: number;
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** CandidateSignalOut */
        CandidateSignalOut: {
            /** Contribution */
            contribution: string;
            /** Explanation */
            explanation: string;
            /** Key */
            key: string;
            /** Label */
            label: string;
            outcome: components["schemas"]["SignalOutcome"];
            /** Raw Value */
            raw_value: {
                [key: string]: unknown;
            } | null;
            rule_kind: components["schemas"]["RuleKind"];
            /** Strength */
            strength: string;
            /** Weight Applied */
            weight_applied: string;
        };
        /**
         * CandidateSort
         * @enum {string}
         */
        CandidateSort: "-score" | "-days_between" | "-detected_at";
        /** CandidateSummaryOut */
        CandidateSummaryOut: {
            band: components["schemas"]["ScoreBand"];
            current_review: components["schemas"]["ReworkReviewOut"] | null;
            customer: components["schemas"]["CandidateCustomerOut"] | null;
            /** Days Between */
            days_between: number;
            /**
             * Detected At
             * Format: date-time
             */
            detected_at: string;
            equipment: components["schemas"]["CandidateEquipmentOut"] | null;
            followup_job: components["schemas"]["CandidateJobOut"];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Suppressed */
            is_suppressed: boolean;
            prior_job: components["schemas"]["CandidateJobOut"];
            /** Score */
            score: string;
            /** Suppressed By Signal Key */
            suppressed_by_signal_key: string | null;
            suppression_reason: components["schemas"]["CandidateSuppressionReason"] | null;
            /** Top Signals */
            top_signals: components["schemas"]["CandidateSignalOut"][];
            workflow_status: components["schemas"]["CandidateWorkflowStatus"];
        };
        /**
         * CandidateSuppressionReason
         * @enum {string}
         */
        CandidateSuppressionReason: "signal_veto" | "out_of_window";
        /**
         * CandidateWorkflowStatus
         * @enum {string}
         */
        CandidateWorkflowStatus: "open" | "in_review" | "reviewed" | "dismissed";
        /**
         * CategoryOutcome
         * @enum {string}
         */
        CategoryOutcome: "rework" | "not_rework" | "uncertain";
        /** ChangePasswordRequest */
        ChangePasswordRequest: {
            /** Current Password */
            current_password: string;
            /** New Password */
            new_password: string;
        };
        /** ChangeRoleRequest */
        ChangeRoleRequest: {
            role: components["schemas"]["OrganizationRole"];
        };
        /** ConfirmEmailChangeRequest */
        ConfirmEmailChangeRequest: {
            /** Token */
            token: string;
        };
        /** ConfirmUploadRequest */
        ConfirmUploadRequest: {
            /**
             * Allow Duplicate
             * @default false
             */
            allow_duplicate: boolean;
        };
        /** ContactRequest */
        ContactRequest: {
            /** Company */
            company?: string | null;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Message */
            message: string;
            /** Name */
            name: string;
            /** Subject */
            subject: string;
            /**
             * Website
             * @default
             */
            website: string;
        };
        /** ContactResponse */
        ContactResponse: {
            /** Detail */
            detail: string;
        };
        /** CreateImportOut */
        CreateImportOut: {
            batch: components["schemas"]["ImportBatchOut"];
            upload: components["schemas"]["PresignedUploadOut"];
        };
        /** CreateImportRequest */
        CreateImportRequest: {
            /** Original Filename */
            original_filename: string;
            /** Source System Id */
            source_system_id?: string | null;
        };
        /** CreateOrganizationRequest */
        CreateOrganizationRequest: {
            /** Name */
            name: string;
        };
        /** CreateReviewRequest */
        CreateReviewRequest: {
            /** Category Id */
            category_id?: string | null;
            decision: components["schemas"]["ReviewDecision"];
            /** Note */
            note?: string | null;
            /** Root Cause Id */
            root_cause_id?: string | null;
        };
        /** DateTransform */
        DateTransform: {
            /** Format */
            format?: string | null;
            /** Timezone */
            timezone?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "date" | "datetime";
        };
        /** DetectedColumnOut */
        DetectedColumnOut: {
            /** Index */
            index: number;
            /** Inferred Type */
            inferred_type: string;
            /** Name */
            name: string;
            /** Sample Values */
            sample_values: string[];
        };
        /** EmailChangeRequest */
        EmailChangeRequest: {
            /**
             * New Email
             * Format: email
             */
            new_email: string;
        };
        /** ErrorReportOut */
        ErrorReportOut: {
            /** Url */
            url: string;
        };
        /** FieldMapping */
        FieldMapping: {
            /** Source Column */
            source_column: string;
            /** Transform */
            transform?: (components["schemas"]["DateTransform"] | components["schemas"]["MoneyTransform"] | components["schemas"]["BooleanTransform"] | components["schemas"]["ValueMapTransform"]) | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ImportBatchOut */
        ImportBatchOut: {
            /** Cancel Requested At */
            cancel_requested_at: string | null;
            /** Completed At */
            completed_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Created Jobs */
            created_jobs: number;
            /** Delimiter */
            delimiter: string | null;
            /** Duplicate Of Batch Id */
            duplicate_of_batch_id: string | null;
            /** Encoding */
            encoding: string | null;
            /** Error Report Ready */
            error_report_ready: boolean;
            /** Error Rows */
            error_rows: number;
            /** Failure Reason */
            failure_reason: string | null;
            /** File Size Bytes */
            file_size_bytes: number | null;
            /** Has Header */
            has_header: boolean | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            mapping: components["schemas"]["MappingDocument"] | null;
            /**
             * Organization Id
             * Format: uuid
             */
            organization_id: string;
            /** Original Filename */
            original_filename: string | null;
            /** Processed Rows */
            processed_rows: number;
            /** Skipped Rows */
            skipped_rows: number;
            /**
             * Source System Id
             * Format: uuid
             */
            source_system_id: string;
            /** Started At */
            started_at: string | null;
            status: components["schemas"]["ImportStatus"];
            /** Total Rows */
            total_rows: number;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Updated Jobs */
            updated_jobs: number;
            /** Warning Rows */
            warning_rows: number;
        };
        /** ImportIssuePageOut */
        ImportIssuePageOut: {
            /** Has More */
            has_more: boolean;
            /** Limit */
            limit: number;
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** ImportIssueRowOut */
        ImportIssueRowOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Issues */
            issues: components["schemas"]["ProfileIssueOut"][];
            /** Row Number */
            row_number: number;
            status: components["schemas"]["ImportRowStatus"];
        };
        /** ImportIssuesOut */
        ImportIssuesOut: {
            /** Data */
            data: components["schemas"]["ImportIssueRowOut"][];
            page: components["schemas"]["ImportIssuePageOut"];
        };
        /** ImportListOut */
        ImportListOut: {
            /** Data */
            data: components["schemas"]["ImportBatchOut"][];
            page: components["schemas"]["ImportPageOut"];
        };
        /** ImportPageOut */
        ImportPageOut: {
            /** Has More */
            has_more: boolean;
            /** Limit */
            limit: number;
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** ImportPreviewOut */
        ImportPreviewOut: {
            /** Approximate Row Count */
            approximate_row_count: number;
            /**
             * Batch Id
             * Format: uuid
             */
            batch_id: string;
            /** Columns */
            columns: components["schemas"]["DetectedColumnOut"][];
            /** Delimiter */
            delimiter: string;
            /** Encoding */
            encoding: string;
            /** Has Header */
            has_header: boolean;
            /** Matched Template Id */
            matched_template_id: string | null;
            /** Profile Issues */
            profile_issues: components["schemas"]["ProfileIssueOut"][];
            /** Sample Rows */
            sample_rows: {
                [key: string]: string;
            }[];
            suggested_mapping: components["schemas"]["MappingDocument"] | null;
            /** Suggestions */
            suggestions: components["schemas"]["MappingSuggestionOut"][];
        };
        /**
         * ImportRowStatus
         * @enum {string}
         */
        ImportRowStatus: "pending" | "imported" | "updated" | "skipped_duplicate" | "skipped_filtered" | "warning" | "error";
        /**
         * ImportStatus
         * @enum {string}
         */
        ImportStatus: "awaiting_file" | "uploaded" | "profiling" | "awaiting_mapping" | "validating" | "validated" | "queued" | "processing" | "completed" | "completed_with_errors" | "failed" | "cancelled";
        /** InvitationOut */
        InvitationOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Email */
            email: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            role: components["schemas"]["OrganizationRole"];
        };
        /** InvitationPreviewOut */
        InvitationPreviewOut: {
            /** Email */
            email: string;
            /** Organization Name */
            organization_name: string;
            role: components["schemas"]["OrganizationRole"];
        };
        /** InviteMemberRequest */
        InviteMemberRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            role: components["schemas"]["OrganizationRole"];
        };
        /**
         * IssueCode
         * @enum {string}
         */
        IssueCode: "MISSING_REQUIRED_FIELD" | "INVALID_DATE" | "AMBIGUOUS_DATE_FORMAT" | "DATE_OUT_OF_RANGE" | "UNRESOLVABLE_CUSTOMER" | "INVALID_NUMBER" | "NUMBER_ROUNDED" | "NEGATIVE_AMOUNT" | "TOO_MANY_COLUMNS" | "TOO_FEW_COLUMNS" | "FIELD_TOO_LONG" | "UNKNOWN_ENUM_VALUE" | "DUPLICATE_ROW_IN_FILE" | "POSSIBLE_DUPLICATE" | "ENCODING_UNCERTAIN" | "ENCODING_REPLACEMENT" | "DELIMITER_UNCERTAIN" | "EQUIPMENT_NOT_RESOLVED" | "ROW_SKIPPED_BY_FILTER";
        /**
         * IssueSeverity
         * @enum {string}
         */
        IssueSeverity: "error" | "warning" | "info";
        /**
         * JobStatus
         * @enum {string}
         */
        JobStatus: "completed" | "cancelled" | "scheduled" | "in_progress" | "unknown";
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** MappingDocument */
        MappingDocument: {
            /** Fields */
            fields: {
                [key: string]: components["schemas"]["FieldMapping"];
            };
            /**
             * Retain Unmapped
             * @default []
             */
            retain_unmapped: string[];
            /**
             * Skip Rows Where
             * @default []
             */
            skip_rows_where: components["schemas"]["SkipFilter"][];
            /**
             * Version
             * @constant
             */
            version: 1;
        };
        /** MappingSuggestionOut */
        MappingSuggestionOut: {
            /** Confidence */
            confidence: number;
            /** Source Column */
            source_column: string;
            strategy: components["schemas"]["SuggestionStrategy"];
            /** Target Field */
            target_field: string;
        };
        /** MembershipOut */
        MembershipOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Joined At
             * Format: date-time
             */
            joined_at: string;
            role: components["schemas"]["OrganizationRole"];
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
        };
        /** MoneyTransform */
        MoneyTransform: {
            /** Decimal Separator */
            decimal_separator?: ("." | ",") | null;
            /** Thousands Separator */
            thousands_separator?: ("." | "," | " ") | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "money";
        };
        /** MyInvitationOut */
        MyInvitationOut: {
            /** Email */
            email: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Organization Id
             * Format: uuid
             */
            organization_id: string;
            /** Organization Name */
            organization_name: string;
            role: components["schemas"]["OrganizationRole"];
        };
        /** MyOrganizationOut */
        MyOrganizationOut: {
            /** Currency Code */
            currency_code: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            role: components["schemas"]["OrganizationRole"];
            /** Slug */
            slug: string;
            /** Status */
            status: string;
            /** Timezone */
            timezone: string;
        };
        /** OrganizationOut */
        OrganizationOut: {
            /** Currency Code */
            currency_code: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** Status */
            status: string;
            /** Timezone */
            timezone: string;
        };
        /**
         * OrganizationRole
         * @enum {string}
         */
        OrganizationRole: "owner" | "admin" | "manager" | "member";
        /** PasswordResetConfirmRequest */
        PasswordResetConfirmRequest: {
            /** New Password */
            new_password: string;
            /** Token */
            token: string;
        };
        /** PasswordResetRequestRequest */
        PasswordResetRequestRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
        };
        /** PresignedUploadOut */
        PresignedUploadOut: {
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Fields */
            fields: {
                [key: string]: string;
            };
            /** Headers */
            headers: {
                [key: string]: string;
            };
            /** Max Bytes */
            max_bytes: number;
            /** Method */
            method: string;
            /** Url */
            url: string;
        };
        /** ProfileIssueOut */
        ProfileIssueOut: {
            code: components["schemas"]["IssueCode"];
            /** Field */
            field?: string | null;
            /** Message */
            message: string;
            /** Raw Value */
            raw_value?: string | null;
            severity: components["schemas"]["IssueSeverity"];
        };
        /** RegisterRequest */
        RegisterRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Full Name */
            full_name: string;
            /** Password */
            password: string;
        };
        /** ResendVerificationRequest */
        ResendVerificationRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
        };
        /**
         * ReviewDecision
         * @enum {string}
         */
        ReviewDecision: "confirmed" | "rejected" | "uncertain";
        /** ReworkCategoryOut */
        ReworkCategoryOut: {
            /** Color */
            color: string | null;
            /** Counts Toward Cost */
            counts_toward_cost: boolean;
            /** Description */
            description: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Active */
            is_active: boolean;
            /** Is System Default */
            is_system_default: boolean;
            /** Key */
            key: string;
            /** Label */
            label: string;
            outcome: components["schemas"]["CategoryOutcome"];
            /** Sort Order */
            sort_order: number;
        };
        /** ReworkReviewOut */
        ReworkReviewOut: {
            /**
             * Candidate Id
             * Format: uuid
             */
            candidate_id: string;
            /** Category Id */
            category_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Decided At
             * Format: date-time
             */
            decided_at: string;
            decision: components["schemas"]["ReviewDecision"];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Note */
            note: string | null;
            /**
             * Reviewed By User Id
             * Format: uuid
             */
            reviewed_by_user_id: string;
            /** Root Cause Id */
            root_cause_id: string | null;
            /** Rule Set Id At Review */
            rule_set_id_at_review: string | null;
            /** Score At Review */
            score_at_review: string | null;
            /** Superseded By Review Id */
            superseded_by_review_id: string | null;
        };
        /** RootCauseOut */
        RootCauseOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Active */
            is_active: boolean;
            /** Is System Default */
            is_system_default: boolean;
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Parent Id */
            parent_id: string | null;
            /** Sort Order */
            sort_order: number;
        };
        /**
         * RuleKind
         * @enum {string}
         */
        RuleKind: "additive" | "multiplier" | "gate" | "veto";
        /**
         * ScoreBand
         * @enum {string}
         */
        ScoreBand: "low" | "medium" | "high";
        /** SessionOut */
        SessionOut: {
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Issued At
             * Format: date-time
             */
            issued_at: string;
            /**
             * Last Seen At
             * Format: date-time
             */
            last_seen_at: string;
            /** User Agent */
            user_agent: string | null;
        };
        /**
         * SignalOutcome
         * @enum {string}
         */
        SignalOutcome: "matched" | "not_matched" | "not_evaluable";
        /** SkipFilter */
        SkipFilter: {
            /** Column */
            column: string;
            /**
             * Operator
             * @enum {string}
             */
            operator: "equals" | "not_equals" | "contains" | "is_empty" | "is_not_empty";
            /** Value */
            value?: string | null;
        };
        /**
         * SuggestionStrategy
         * @enum {string}
         */
        SuggestionStrategy: "synonym" | "fuzzy";
        /** TransferOwnershipRequest */
        TransferOwnershipRequest: {
            /**
             * To User Id
             * Format: uuid
             */
            to_user_id: string;
        };
        /** UpdateProfileRequest */
        UpdateProfileRequest: {
            /** Full Name */
            full_name?: string | null;
            /** Timezone */
            timezone?: string | null;
        };
        /** UserOut */
        UserOut: {
            /** Email */
            email: string;
            /** Email Verified At */
            email_verified_at: string | null;
            /** Full Name */
            full_name: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Status */
            status: string;
            /** Timezone */
            timezone: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** ValueMapTransform */
        ValueMapTransform: {
            /** Map */
            map: {
                [key: string]: string;
            };
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "value_map";
        };
        /** VerifyEmailRequest */
        VerifyEmailRequest: {
            /** Token */
            token: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    confirmEmailChange: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmEmailChangeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    acceptInvitation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AcceptInvitationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MembershipOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    previewInvitation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvitationPreviewOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    logoutAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    passwordResetConfirm: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetConfirmRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    passwordResetRequest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetRequestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resendVerification: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResendVerificationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verifyEmail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyEmailRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submitContact: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContactRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContactResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    updateMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProfileRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    requestEmailChange: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailChangeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listMyInvitations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MyInvitationOut"][];
                };
            };
        };
    };
    changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listMySessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"][];
                };
            };
        };
    };
    revokeMySession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listMyOrganizations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MyOrganizationOut"][];
                };
            };
        };
    };
    createOrganization: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrganizationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getOrganization: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listAudit: {
        parameters: {
            query?: {
                action?: string | null;
                actor_user_id?: string | null;
                resource_type?: string | null;
                resource_id?: string | null;
                occurred_from?: string | null;
                occurred_to?: string | null;
                cursor?: string | null;
                limit?: number | null;
            };
            header?: never;
            path: {
                org_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    exportAudit: {
        parameters: {
            query?: {
                action?: string | null;
                actor_user_id?: string | null;
                resource_type?: string | null;
                resource_id?: string | null;
                occurred_from?: string | null;
                occurred_to?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                org_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listImports: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number | null;
            };
            header?: never;
            path: {
                org_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    createImport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateImportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateImportOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getImport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org_id: string;
                batch_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportBatchOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancelImport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org_id: string;
                batch_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportBatchOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    commitImport: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                org_id: string;
                batch_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportBatchOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listImportIssues: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number | null;
            };
            header?: never;
            path: {
                org_id: string;
                batch_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportIssuesOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    exportImportIssues: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org_id: string;
                batch_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorReportOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    applyMapping: {
        parameters: {
            query?: {
                template_id?: string | null;
            };
            header?: never;
            path: {
                org_id: string;
                batch_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MappingDocument"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportBatchOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    previewImport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org_id: string;
                batch_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportPreviewOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirmUpload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org_id: string;
                batch_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ConfirmUploadRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportBatchOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validateImport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org_id: string;
                batch_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportBatchOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listInvitations: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvitationOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    createInvitation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InviteMemberRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvitationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revokeInvitation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org_id: string;
                invitation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resendInvitation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org_id: string;
                invitation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvitationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listMembers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MembershipOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    transferOwnership: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransferOwnershipRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    removeMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org_id: string;
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    changeMemberRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org_id: string;
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangeRoleRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MembershipOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listCandidates: {
        parameters: {
            query?: {
                min_score?: number | string | null;
                band?: components["schemas"]["ScoreBand"] | null;
                status?: components["schemas"]["CandidateWorkflowStatus"];
                include_suppressed?: boolean;
                customer_id?: string | null;
                equipment_id?: string | null;
                technician_id?: string | null;
                date_from?: string | null;
                date_to?: string | null;
                sort?: components["schemas"]["CandidateSort"];
                cursor?: string | null;
                limit?: number | null;
            };
            header?: never;
            path: {
                org_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidateListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getCandidate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org_id: string;
                candidate_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidateDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    createReview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org_id: string;
                candidate_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateReviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReworkReviewOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listReviewHistory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org_id: string;
                candidate_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReworkReviewOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listReviewCategories: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReworkCategoryOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listRootCauses: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RootCauseOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    ready: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
