"""identity organizations audit

users/user_credentials/user_sessions/*_tokens/organizations get NO RLS —
they are not tenant-owned (docs/architecture/02-multi-tenancy.md §1).
organization_memberships and organization_invitations get the
dual-clause policies from migrations/rls_helpers.py — see that module's
docstring for why the plain `enable_rls` doesn't fit either table.
audit_events gets the standard policy PLUS a revoked UPDATE/DELETE grant
— append-only enforced by Postgres, not convention (13-audit.md §2).

This migration also retires `_rls_smoke_test` (from the Phase 2
migration, cbd4f94adbcf) now that real tenant tables exist to prove the
mechanism against — see tests/security/test_rls.py, rewritten in this
same step to exercise organization_memberships/organization_invitations
directly instead of the synthetic fixture.

Revision ID: 52ffdd774e8b
Revises: cbd4f94adbcf
Create Date: 2026-09-19 00:11:41.175160
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from migrations.rls_helpers import (
    disable_rls,
    enable_rls,
    enable_rls_with_self_access,
    enable_rls_with_token_lookup,
)

revision: str = '52ffdd774e8b'
down_revision: str | None = 'cbd4f94adbcf'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS citext")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', postgresql.CITEXT(), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default='pending_verification', nullable=False),
    sa.Column('email_verified_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('last_login_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('timezone', sa.Text(), nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='users_email_key')
    )
    op.create_table('audit_events',
    sa.Column('actor_type', sa.Text(), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('actor_label', sa.Text(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('resource_type', sa.Text(), nullable=True),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('request_id', sa.Text(), nullable=True),
    sa.Column('ip_hash', sa.Text(), nullable=True),
    sa.Column('occurred_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('audit_events_org_action_occurred_idx', 'audit_events', ['organization_id', 'action', 'occurred_at'], unique=False)
    op.create_index('audit_events_org_occurred_idx', 'audit_events', ['organization_id', 'occurred_at'], unique=False)
    op.create_index('audit_events_org_resource_idx', 'audit_events', ['organization_id', 'resource_type', 'resource_id'], unique=False)
    op.create_index(op.f('ix_audit_events_organization_id'), 'audit_events', ['organization_id'], unique=False)
    op.create_table('email_verification_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('consumed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash', name='email_verification_tokens_hash_key')
    )
    op.create_table('organization_invitations',
    sa.Column('email', postgresql.CITEXT(), nullable=False),
    sa.Column('role', sa.Text(), server_default='member', nullable=False),
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('invited_by_user_id', sa.UUID(), nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('accepted_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('accepted_by_user_id', sa.UUID(), nullable=True),
    sa.Column('revoked_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['accepted_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['invited_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash', name='organization_invitations_token_hash_key')
    )
    op.create_index(op.f('ix_organization_invitations_organization_id'), 'organization_invitations', ['organization_id'], unique=False)
    op.create_index('organization_invitations_org_email_pending_idx', 'organization_invitations', ['organization_id', 'email'], unique=True, postgresql_where=sa.text('accepted_at IS NULL AND revoked_at IS NULL'))
    op.create_table('organization_memberships',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('invited_by_user_id', sa.UUID(), nullable=True),
    sa.Column('joined_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['invited_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'id', name='organization_memberships_org_id_key')
    )
    op.create_index(op.f('ix_organization_memberships_organization_id'), 'organization_memberships', ['organization_id'], unique=False)
    op.create_index('organization_memberships_org_role_active_idx', 'organization_memberships', ['organization_id', 'role'], unique=False, postgresql_where=sa.text('revoked_at IS NULL'))
    op.create_index('organization_memberships_org_user_active_idx', 'organization_memberships', ['organization_id', 'user_id'], unique=True, postgresql_where=sa.text('revoked_at IS NULL'))
    op.create_index('organization_memberships_user_active_idx', 'organization_memberships', ['user_id'], unique=False, postgresql_where=sa.text('revoked_at IS NULL'))
    op.create_table('organizations',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('slug', postgresql.CITEXT(), nullable=False),
    sa.Column('timezone', sa.Text(), server_default='UTC', nullable=False),
    sa.Column('currency_code', sa.Text(), server_default='USD', nullable=False),
    sa.Column('industry_key', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), server_default='active', nullable=False),
    sa.Column('onboarding_completed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('purge_after', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', name='organizations_slug_key')
    )
    op.create_table('password_reset_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('consumed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('expires_at > created_at', name='password_reset_tokens_expiry_check'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash', name='password_reset_tokens_hash_key')
    )
    op.create_table('user_credentials',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('password_updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('failed_attempt_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('locked_until', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('issued_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('last_seen_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('ip_hash', sa.Text(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash', name='user_sessions_token_hash_key')
    )
    op.create_index('user_sessions_user_id_revoked_at_idx', 'user_sessions', ['user_id', 'revoked_at'], unique=False)
    op.drop_index(op.f('_rls_smoke_test_org_idx'), table_name='_rls_smoke_test')
    op.drop_table('_rls_smoke_test')
    # ### end Alembic commands ###

    enable_rls_with_self_access("organization_memberships")
    enable_rls_with_token_lookup("organization_invitations")
    enable_rls("audit_events")

    # Append-only — see 13-audit.md §2. The DEFAULT PRIVILEGES grant in
    # infra/neon/bootstrap.sql hands secondtrip_app UPDATE/DELETE on
    # every table by default; this table is the one deliberate exception.
    op.execute("REVOKE UPDATE, DELETE ON audit_events FROM secondtrip_app")


def downgrade() -> None:
    disable_rls("audit_events")
    disable_rls("organization_invitations")
    disable_rls("organization_memberships")
    op.execute("GRANT UPDATE, DELETE ON audit_events TO secondtrip_app")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_rls_smoke_test',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('label', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('_rls_smoke_test_pkey'))
    )
    op.create_index(op.f('_rls_smoke_test_org_idx'), '_rls_smoke_test', ['organization_id'], unique=False)
    enable_rls("_rls_smoke_test")  # restore what the previous migration applied
    op.drop_index('user_sessions_user_id_revoked_at_idx', table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_table('user_credentials')
    op.drop_table('password_reset_tokens')
    op.drop_table('organizations')
    op.drop_index('organization_memberships_user_active_idx', table_name='organization_memberships', postgresql_where=sa.text('revoked_at IS NULL'))
    op.drop_index('organization_memberships_org_user_active_idx', table_name='organization_memberships', postgresql_where=sa.text('revoked_at IS NULL'))
    op.drop_index('organization_memberships_org_role_active_idx', table_name='organization_memberships', postgresql_where=sa.text('revoked_at IS NULL'))
    op.drop_index(op.f('ix_organization_memberships_organization_id'), table_name='organization_memberships')
    op.drop_table('organization_memberships')
    op.drop_index('organization_invitations_org_email_pending_idx', table_name='organization_invitations', postgresql_where=sa.text('accepted_at IS NULL AND revoked_at IS NULL'))
    op.drop_index(op.f('ix_organization_invitations_organization_id'), table_name='organization_invitations')
    op.drop_table('organization_invitations')
    op.drop_table('email_verification_tokens')
    op.drop_index(op.f('ix_audit_events_organization_id'), table_name='audit_events')
    op.drop_index('audit_events_org_resource_idx', table_name='audit_events')
    op.drop_index('audit_events_org_occurred_idx', table_name='audit_events')
    op.drop_index('audit_events_org_action_occurred_idx', table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_table('users')
    # ### end Alembic commands ###
