"""phase4 ingestion foundation

Revision ID: 9ee6a75b5acd
Revises: a47d9c3e1f20
Create Date: 2026-09-19 20:43:39.080028
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from migrations.rls_helpers import (
    disable_rls,
    enable_rls,
    enable_rls_with_worker_access,
)

revision: str = "9ee6a75b5acd"
down_revision: str | None = "a47d9c3e1f20"
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None

TENANT_TABLES = (
    "api_idempotency_records",
    "organization_entitlement_overrides",
    "organization_subscriptions",
    "service_categories",
    "source_systems",
    "technicians",
    "usage_counters",
    "customers",
    "import_column_mappings",
    "import_batches",
    "locations",
    "equipment",
    "jobs",
    "import_rows",
    "job_line_items",
    "job_notes",
)
WORKER_TABLES = ("background_jobs", "billing_events")


def _seed_plans_and_entitlements() -> None:
    op.execute(
        """
        INSERT INTO plans (key, name, sort_order)
        VALUES ('free', 'Free', 10), ('pro', 'Pro', 20), ('business', 'Business', 30)
        """
    )
    op.execute(
        """
        INSERT INTO plan_entitlements
            (plan_id, entitlement_key, limit_value, is_boolean, period)
        SELECT plans.id, seed.entitlement_key, seed.limit_value, seed.is_boolean, seed.period
        FROM plans
        JOIN (VALUES
            ('free', 'jobs_imported', 5000, false, 'month'),
            ('pro', 'jobs_imported', 100000, false, 'month'),
            ('business', 'jobs_imported', 1000000, false, 'month'),
            ('free', 'jobs_retained', 10000, false, 'total'),
            ('pro', 'jobs_retained', 500000, false, 'total'),
            ('business', 'jobs_retained', NULL, false, 'total'),
            ('free', 'retention_months', 6, false, 'total'),
            ('pro', 'retention_months', 24, false, 'total'),
            ('business', 'retention_months', 84, false, 'total'),
            ('free', 'import_file_bytes', 5242880, false, 'operation'),
            ('pro', 'import_file_bytes', 52428800, false, 'operation'),
            ('business', 'import_file_bytes', 209715200, false, 'operation'),
            ('free', 'imports_per_month', 3, false, 'month'),
            ('pro', 'imports_per_month', 50, false, 'month'),
            ('business', 'imports_per_month', NULL, false, 'month'),
            ('free', 'concurrent_imports', 1, false, 'concurrent'),
            ('pro', 'concurrent_imports', 2, false, 'concurrent'),
            ('business', 'concurrent_imports', 3, false, 'concurrent'),
            ('free', 'team_members', 2, false, 'total'),
            ('pro', 'team_members', 10, false, 'total'),
            ('business', 'team_members', NULL, false, 'total'),
            ('free', 'ai_analyses', 0, false, 'month'),
            ('pro', 'ai_analyses', 500, false, 'month'),
            ('business', 'ai_analyses', 5000, false, 'month'),
            ('free', 'ai_spend_cents', 0, false, 'month'),
            ('pro', 'ai_spend_cents', 500, false, 'month'),
            ('business', 'ai_spend_cents', 5000, false, 'month'),
            ('free', 'embeddings_enabled', 1, true, NULL),
            ('pro', 'embeddings_enabled', 1, true, NULL),
            ('business', 'embeddings_enabled', 1, true, NULL),
            ('free', 'exports_enabled', 1, true, NULL),
            ('pro', 'exports_enabled', 1, true, NULL),
            ('business', 'exports_enabled', 1, true, NULL),
            ('free', 'exports_per_month', 5, false, 'month'),
            ('pro', 'exports_per_month', 100, false, 'month'),
            ('business', 'exports_per_month', NULL, false, 'month'),
            ('free', 'api_access', 0, true, NULL),
            ('pro', 'api_access', 0, true, NULL),
            ('business', 'api_access', 1, true, NULL),
            ('free', 'integrations', 0, true, NULL),
            ('pro', 'integrations', 0, true, NULL),
            ('business', 'integrations', 1, true, NULL),
            ('free', 'custom_detection_rules', 0, true, NULL),
            ('pro', 'custom_detection_rules', 1, true, NULL),
            ('business', 'custom_detection_rules', 1, true, NULL),
            ('free', 'audit_retention_months', 3, false, 'total'),
            ('pro', 'audit_retention_months', 24, false, 'total'),
            ('business', 'audit_retention_months', 84, false, 'total')
        ) AS seed(plan_key, entitlement_key, limit_value, is_boolean, period)
            ON seed.plan_key = plans.key
        """
    )


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "plans",
        sa.Column("key", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("monthly_price_amount", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("annual_price_amount", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("currency_code", sa.Text(), server_default="USD", nullable=False),
        sa.Column("is_public", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key", name="plans_key_key"),
    )
    op.create_table(
        "plan_entitlements",
        sa.Column("plan_id", sa.UUID(), nullable=False),
        sa.Column("entitlement_key", sa.Text(), nullable=False),
        sa.Column("limit_value", sa.BigInteger(), nullable=True),
        sa.Column("is_boolean", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("period", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.ForeignKeyConstraint(["plan_id"], ["plans.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("plan_id", "entitlement_key", name="plan_entitlements_plan_key"),
    )
    op.create_table(
        "api_idempotency_records",
        sa.Column("route", sa.Text(), nullable=False),
        sa.Column("idempotency_key", sa.Text(), nullable=False),
        sa.Column("request_hash", sa.LargeBinary(), nullable=False),
        sa.Column("response_status", sa.Integer(), nullable=True),
        sa.Column("response_body", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "response_headers",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id", "route", "idempotency_key", name="api_idempotency_route_key"
        ),
    )
    op.create_index(
        "api_idempotency_expires_idx", "api_idempotency_records", ["expires_at"], unique=False
    )
    op.create_index(
        op.f("ix_api_idempotency_records_organization_id"),
        "api_idempotency_records",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "background_jobs",
        sa.Column("organization_id", sa.UUID(), nullable=True),
        sa.Column("job_type", sa.Text(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "queued",
                "processing",
                "completed",
                "failed",
                "cancelled",
                name="bg_job_status",
            ),
            server_default="queued",
            nullable=False,
        ),
        sa.Column("priority", sa.Integer(), server_default=sa.text("100"), nullable=False),
        sa.Column(
            "run_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("attempts", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("max_attempts", sa.Integer(), server_default=sa.text("5"), nullable=False),
        sa.Column("locked_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("locked_by", sa.Text(), nullable=True),
        sa.Column("heartbeat_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("idempotency_key", sa.Text(), nullable=True),
        sa.Column(
            "cancel_requested", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("enqueued_by_user_id", sa.UUID(), nullable=True),
        sa.Column("correlation_id", sa.Text(), nullable=True),
        sa.Column("completed_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["enqueued_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "background_jobs_active_idempotency_key",
        "background_jobs",
        ["job_type", "idempotency_key"],
        unique=True,
        postgresql_where=sa.text("idempotency_key IS NOT NULL AND status <> 'failed'"),
    )
    op.create_index(
        "background_jobs_claim_idx",
        "background_jobs",
        ["status", "run_at", "priority"],
        unique=False,
        postgresql_where=sa.text("status = 'queued'"),
    )
    op.create_index(
        "background_jobs_org_type_created_idx",
        "background_jobs",
        ["organization_id", "job_type", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        "background_jobs_stale_idx",
        "background_jobs",
        ["status", "heartbeat_at"],
        unique=False,
        postgresql_where=sa.text("status = 'processing'"),
    )
    op.create_index(
        op.f("ix_background_jobs_organization_id"),
        "background_jobs",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "billing_events",
        sa.Column("organization_id", sa.UUID(), nullable=True),
        sa.Column("provider", sa.Text(), nullable=False),
        sa.Column("provider_event_id", sa.Text(), nullable=False),
        sa.Column("event_type", sa.Text(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("signature_verified", sa.Boolean(), nullable=False),
        sa.Column("status", sa.Text(), server_default="pending", nullable=False),
        sa.Column("processed_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "provider", "provider_event_id", name="billing_events_provider_event_key"
        ),
    )
    op.create_index(
        "billing_events_org_created_idx",
        "billing_events",
        ["organization_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        op.f("ix_billing_events_organization_id"),
        "billing_events",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "organization_entitlement_overrides",
        sa.Column("entitlement_key", sa.Text(), nullable=False),
        sa.Column("limit_value", sa.BigInteger(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("expires_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id", "entitlement_key", name="organization_entitlement_overrides_org_key"
        ),
    )
    op.create_index(
        op.f("ix_organization_entitlement_overrides_organization_id"),
        "organization_entitlement_overrides",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "organization_subscriptions",
        sa.Column("plan_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.Text(), server_default="active", nullable=False),
        sa.Column("billing_provider", sa.Text(), server_default="noop", nullable=False),
        sa.Column("provider_customer_id", sa.Text(), nullable=True),
        sa.Column("provider_subscription_id", sa.Text(), nullable=True),
        sa.Column("current_period_start", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("current_period_end", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "cancel_at_period_end", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("trial_ends_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["plans.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", name="organization_subscriptions_org_key"),
    )
    op.create_index(
        op.f("ix_organization_subscriptions_organization_id"),
        "organization_subscriptions",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "service_categories",
        sa.Column("key", sa.Text(), nullable=False),
        sa.Column("label", sa.Text(), nullable=False),
        sa.Column("parent_id", sa.UUID(), nullable=True),
        sa.Column(
            "is_system_default", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["parent_id"], ["service_categories.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["organization_id", "parent_id"],
            ["service_categories.organization_id", "service_categories.id"],
            name="service_categories_parent_tenant_fkey",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "id", name="service_categories_org_id_key"),
        sa.UniqueConstraint("organization_id", "key", name="service_categories_org_key_key"),
    )
    op.create_index(
        op.f("ix_service_categories_organization_id"),
        "service_categories",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "source_systems",
        sa.Column(
            "kind",
            sa.Enum(
                "csv_upload",
                "api",
                "servicetitan",
                "jobber",
                "housecall_pro",
                name="source_system_kind",
            ),
            nullable=False,
        ),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("is_default", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "id", name="source_systems_org_id_key"),
        sa.UniqueConstraint("organization_id", "name", name="source_systems_org_name_key"),
    )
    op.create_index(
        op.f("ix_source_systems_organization_id"),
        "source_systems",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "technicians",
        sa.Column("external_id", sa.Text(), nullable=True),
        sa.Column("natural_key_hash", sa.LargeBinary(), nullable=False),
        sa.Column("full_name", sa.Text(), nullable=False),
        sa.Column("normalized_name", sa.Text(), nullable=False),
        sa.Column("employee_code", sa.Text(), nullable=True),
        sa.Column("email", postgresql.CITEXT(), nullable=True),
        sa.Column("hourly_cost_amount", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("currency_code", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("deleted_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "id", name="technicians_org_id_key"),
    )
    op.create_index(
        op.f("ix_technicians_organization_id"), "technicians", ["organization_id"], unique=False
    )
    op.create_index(
        "technicians_org_natural_key",
        "technicians",
        ["organization_id", "natural_key_hash"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "usage_counters",
        sa.Column("metric_key", sa.Text(), nullable=False),
        sa.Column("period_start", sa.Date(), nullable=False),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column("value", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id", "metric_key", "period_start", name="usage_counters_org_period_key"
        ),
    )
    op.create_index(
        op.f("ix_usage_counters_organization_id"),
        "usage_counters",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "customers",
        sa.Column("source_system_id", sa.UUID(), nullable=True),
        sa.Column("external_id", sa.Text(), nullable=True),
        sa.Column("natural_key_hash", sa.LargeBinary(), nullable=False),
        sa.Column("display_name", sa.Text(), nullable=False),
        sa.Column("normalized_name", sa.Text(), nullable=False),
        sa.Column("customer_type", sa.Text(), nullable=True),
        sa.Column("email", postgresql.CITEXT(), nullable=True),
        sa.Column("phone_raw", sa.Text(), nullable=True),
        sa.Column("phone_e164", sa.Text(), nullable=True),
        sa.Column("account_number", sa.Text(), nullable=True),
        sa.Column("first_seen_job_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("last_seen_job_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("job_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("deleted_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "source_system_id"],
            ["source_systems.organization_id", "source_systems.id"],
            name="customers_source_system_fkey",
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "id", name="customers_org_id_key"),
    )
    op.create_index(
        "customers_org_natural_key",
        "customers",
        ["organization_id", "natural_key_hash"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(
        "customers_org_normalized_name_idx",
        "customers",
        ["organization_id", "normalized_name"],
        unique=False,
    )
    op.create_index(
        "customers_org_phone_idx",
        "customers",
        ["organization_id", "phone_e164"],
        unique=False,
        postgresql_where=sa.text("phone_e164 IS NOT NULL"),
    )
    op.create_index(
        "customers_org_source_external_key",
        "customers",
        ["organization_id", "source_system_id", "external_id"],
        unique=True,
        postgresql_where=sa.text("external_id IS NOT NULL AND deleted_at IS NULL"),
    )
    op.create_index(
        op.f("ix_customers_organization_id"), "customers", ["organization_id"], unique=False
    )
    op.create_table(
        "import_column_mappings",
        sa.Column("source_system_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("mapping", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "options",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("is_default", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("signature", sa.Text(), nullable=True),
        sa.Column("usage_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("last_used_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("created_by_user_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["created_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["source_system_id"], ["source_systems.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["organization_id", "source_system_id"],
            ["source_systems.organization_id", "source_systems.id"],
            name="import_column_mappings_source_system_tenant_fkey",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "id", name="import_column_mappings_org_id_key"),
        sa.UniqueConstraint("organization_id", "name", name="import_column_mappings_org_name_key"),
    )
    op.create_index(
        "import_column_mappings_org_signature_idx",
        "import_column_mappings",
        ["organization_id", "signature"],
        unique=False,
    )
    op.create_index(
        op.f("ix_import_column_mappings_organization_id"),
        "import_column_mappings",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "import_batches",
        sa.Column("source_system_id", sa.UUID(), nullable=False),
        sa.Column("created_by_user_id", sa.UUID(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "awaiting_file",
                "uploaded",
                "profiling",
                "awaiting_mapping",
                "validating",
                "validated",
                "queued",
                "processing",
                "completed",
                "completed_with_errors",
                "failed",
                "cancelled",
                name="import_status",
            ),
            server_default="awaiting_file",
            nullable=False,
        ),
        sa.Column("original_filename", sa.Text(), nullable=True),
        sa.Column("storage_key", sa.Text(), nullable=True),
        sa.Column("file_size_bytes", sa.BigInteger(), nullable=True),
        sa.Column("file_sha256", sa.LargeBinary(), nullable=True),
        sa.Column("duplicate_of_batch_id", sa.UUID(), nullable=True),
        sa.Column("encoding", sa.Text(), nullable=True),
        sa.Column("delimiter", sa.String(length=1), nullable=True),
        sa.Column("has_header", sa.Boolean(), nullable=True),
        sa.Column("detected_columns", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("sample_rows", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("mapping", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("template_id", sa.UUID(), nullable=True),
        sa.Column("total_rows", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("processed_rows", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("created_jobs", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("updated_jobs", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("skipped_rows", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("warning_rows", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("error_rows", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("error_report_key", sa.Text(), nullable=True),
        sa.Column("cancel_requested_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("failure_reason", sa.Text(), nullable=True),
        sa.Column("started_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("completed_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["created_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["duplicate_of_batch_id"], ["import_batches.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "duplicate_of_batch_id"],
            ["import_batches.organization_id", "import_batches.id"],
            name="import_batches_duplicate_of_tenant_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "source_system_id"],
            ["source_systems.organization_id", "source_systems.id"],
            name="import_batches_source_system_fkey",
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["template_id"], ["import_column_mappings.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "template_id"],
            ["import_column_mappings.organization_id", "import_column_mappings.id"],
            name="import_batches_template_tenant_fkey",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "id", name="import_batches_org_id_key"),
    )
    op.create_index(
        "import_batches_org_active_idx",
        "import_batches",
        ["organization_id", "status"],
        unique=False,
        postgresql_where=sa.text("status IN ('queued', 'processing')"),
    )
    op.create_index(
        "import_batches_org_created_idx",
        "import_batches",
        ["organization_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        "import_batches_org_file_hash_key",
        "import_batches",
        ["organization_id", "file_sha256"],
        unique=True,
        postgresql_where=sa.text(
            "file_sha256 IS NOT NULL AND deleted_at IS NULL AND duplicate_of_batch_id IS NULL"
        ),
    )
    op.create_index(
        op.f("ix_import_batches_organization_id"),
        "import_batches",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "locations",
        sa.Column("customer_id", sa.UUID(), nullable=True),
        sa.Column("external_id", sa.Text(), nullable=True),
        sa.Column("address_hash", sa.LargeBinary(), nullable=False),
        sa.Column("label", sa.Text(), nullable=True),
        sa.Column("address_line1", sa.Text(), nullable=True),
        sa.Column("address_line2", sa.Text(), nullable=True),
        sa.Column("city", sa.Text(), nullable=True),
        sa.Column("region", sa.Text(), nullable=True),
        sa.Column("postal_code", sa.Text(), nullable=True),
        sa.Column("country_code", sa.Text(), nullable=True),
        sa.Column("latitude", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("longitude", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("deleted_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "customer_id"],
            ["customers.organization_id", "customers.id"],
            name="locations_customer_fkey",
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "id", name="locations_org_id_key"),
    )
    op.create_index(
        op.f("ix_locations_organization_id"), "locations", ["organization_id"], unique=False
    )
    op.create_index(
        "locations_org_customer_address_key",
        "locations",
        ["organization_id", "customer_id", "address_hash"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(
        "locations_org_postal_code_idx",
        "locations",
        ["organization_id", "postal_code"],
        unique=False,
    )
    op.create_table(
        "equipment",
        sa.Column("customer_id", sa.UUID(), nullable=True),
        sa.Column("location_id", sa.UUID(), nullable=True),
        sa.Column("external_id", sa.Text(), nullable=True),
        sa.Column("natural_key_hash", sa.LargeBinary(), nullable=False),
        sa.Column("asset_tag", sa.Text(), nullable=True),
        sa.Column("serial_number", sa.Text(), nullable=True),
        sa.Column("manufacturer", sa.Text(), nullable=True),
        sa.Column("model", sa.Text(), nullable=True),
        sa.Column("equipment_type", sa.Text(), nullable=True),
        sa.Column("installed_on", sa.Date(), nullable=True),
        sa.Column("warranty_expires_on", sa.Date(), nullable=True),
        sa.Column("deleted_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "customer_id"],
            ["customers.organization_id", "customers.id"],
            name="equipment_customer_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "location_id"],
            ["locations.organization_id", "locations.id"],
            name="equipment_location_fkey",
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "id", name="equipment_org_id_key"),
    )
    op.create_index(
        "equipment_org_location_idx", "equipment", ["organization_id", "location_id"], unique=False
    )
    op.create_index(
        "equipment_org_natural_key",
        "equipment",
        ["organization_id", "natural_key_hash"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(
        "equipment_org_serial_idx",
        "equipment",
        ["organization_id", "serial_number"],
        unique=False,
        postgresql_where=sa.text("serial_number IS NOT NULL"),
    )
    op.create_index(
        op.f("ix_equipment_organization_id"), "equipment", ["organization_id"], unique=False
    )
    op.create_table(
        "jobs",
        sa.Column("source_system_id", sa.UUID(), nullable=False),
        sa.Column("external_id", sa.Text(), nullable=True),
        sa.Column("natural_key_hash", sa.LargeBinary(), nullable=False),
        sa.Column("first_import_batch_id", sa.UUID(), nullable=True),
        sa.Column("last_import_batch_id", sa.UUID(), nullable=True),
        sa.Column("customer_id", sa.UUID(), nullable=True),
        sa.Column("location_id", sa.UUID(), nullable=True),
        sa.Column("equipment_id", sa.UUID(), nullable=True),
        sa.Column("technician_id", sa.UUID(), nullable=True),
        sa.Column("service_category_id", sa.UUID(), nullable=True),
        sa.Column("job_number", sa.Text(), nullable=True),
        sa.Column("raw_service_category", sa.Text(), nullable=True),
        sa.Column("raw_job_type", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "completed", "cancelled", "scheduled", "in_progress", "unknown", name="job_status"
            ),
            server_default="unknown",
            nullable=False,
        ),
        sa.Column("scheduled_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("started_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("completed_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("service_date", sa.Date(), nullable=False),
        sa.Column("duration_minutes", sa.Integer(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("symptoms_text", sa.Text(), nullable=True),
        sa.Column("diagnosis_text", sa.Text(), nullable=True),
        sa.Column("resolution_text", sa.Text(), nullable=True),
        sa.Column("invoice_number", sa.Text(), nullable=True),
        sa.Column("revenue_amount", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("parts_amount", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("labor_amount", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("currency_code", sa.Text(), nullable=False),
        sa.Column("is_warranty", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("is_no_charge", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("warranty_reference", sa.Text(), nullable=True),
        sa.Column(
            "extra_fields",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "search_document",
            postgresql.TSVECTOR(),
            sa.Computed(
                "to_tsvector('simple', coalesce(summary, '') || ' ' || coalesce(description, '') || ' ' || coalesce(symptoms_text, '') || ' ' || coalesce(diagnosis_text, '') || ' ' || coalesce(resolution_text, ''))",
                persisted=True,
            ),
            nullable=False,
        ),
        sa.Column("embedding_content_hash", sa.LargeBinary(), nullable=True),
        sa.Column("deleted_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["first_import_batch_id"], ["import_batches.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["last_import_batch_id"], ["import_batches.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "first_import_batch_id"],
            ["import_batches.organization_id", "import_batches.id"],
            name="jobs_first_import_batch_tenant_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "last_import_batch_id"],
            ["import_batches.organization_id", "import_batches.id"],
            name="jobs_last_import_batch_tenant_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "customer_id"],
            ["customers.organization_id", "customers.id"],
            name="jobs_customer_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "equipment_id"],
            ["equipment.organization_id", "equipment.id"],
            name="jobs_equipment_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "location_id"],
            ["locations.organization_id", "locations.id"],
            name="jobs_location_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "service_category_id"],
            ["service_categories.organization_id", "service_categories.id"],
            name="jobs_service_category_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "source_system_id"],
            ["source_systems.organization_id", "source_systems.id"],
            name="jobs_source_system_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "technician_id"],
            ["technicians.organization_id", "technicians.id"],
            name="jobs_technician_fkey",
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "id", name="jobs_org_id_key"),
    )
    op.create_index(op.f("ix_jobs_organization_id"), "jobs", ["organization_id"], unique=False)
    op.create_index(
        "jobs_org_customer_date_idx",
        "jobs",
        ["organization_id", "customer_id", "service_date"],
        unique=False,
    )
    op.create_index(
        "jobs_org_date_id_idx",
        "jobs",
        ["organization_id", sa.literal_column("service_date DESC"), sa.literal_column("id DESC")],
        unique=False,
    )
    op.create_index(
        "jobs_org_embedding_hash_idx",
        "jobs",
        ["organization_id", "embedding_content_hash"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(
        "jobs_org_equipment_date_idx",
        "jobs",
        ["organization_id", "equipment_id", "service_date"],
        unique=False,
        postgresql_where=sa.text("equipment_id IS NOT NULL"),
    )
    op.create_index(
        "jobs_org_last_import_idx",
        "jobs",
        ["organization_id", "last_import_batch_id"],
        unique=False,
    )
    op.create_index(
        "jobs_org_location_date_idx",
        "jobs",
        ["organization_id", "location_id", "service_date"],
        unique=False,
        postgresql_where=sa.text("location_id IS NOT NULL"),
    )
    op.create_index(
        "jobs_org_natural_key",
        "jobs",
        ["organization_id", "natural_key_hash"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(
        "jobs_org_source_external_key",
        "jobs",
        ["organization_id", "source_system_id", "external_id"],
        unique=True,
        postgresql_where=sa.text("external_id IS NOT NULL AND deleted_at IS NULL"),
    )
    op.create_index(
        "jobs_org_technician_date_idx",
        "jobs",
        ["organization_id", "technician_id", "service_date"],
        unique=False,
    )
    op.create_index(
        "jobs_search_document_idx",
        "jobs",
        ["search_document"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_table(
        "import_rows",
        sa.Column("import_batch_id", sa.UUID(), nullable=False),
        sa.Column("row_number", sa.Integer(), nullable=False),
        sa.Column("raw_data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("row_hash", sa.LargeBinary(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "imported",
                "updated",
                "skipped_duplicate",
                "skipped_filtered",
                "warning",
                "error",
                name="import_row_status",
            ),
            server_default="pending",
            nullable=False,
        ),
        sa.Column(
            "issues",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("job_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["organization_id", "job_id"],
            ["jobs.organization_id", "jobs.id"],
            name="import_rows_job_tenant_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "import_batch_id"],
            ["import_batches.organization_id", "import_batches.id"],
            name="import_rows_batch_fkey",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("import_batch_id", "row_number", name="import_rows_batch_row_key"),
    )
    op.create_index(
        "import_rows_batch_status_idx", "import_rows", ["import_batch_id", "status"], unique=False
    )
    op.create_index(
        "import_rows_org_batch_idx",
        "import_rows",
        ["organization_id", "import_batch_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_import_rows_organization_id"), "import_rows", ["organization_id"], unique=False
    )
    op.create_table(
        "job_line_items",
        sa.Column("job_id", sa.UUID(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("part", "labor", "fee", "discount", "other", name="line_item_kind"),
            nullable=False,
        ),
        sa.Column("code", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "quantity", sa.Numeric(precision=12, scale=3), server_default="1", nullable=False
        ),
        sa.Column("unit_amount", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("total_amount", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("currency_code", sa.Text(), nullable=False),
        sa.Column("line_number", sa.Integer(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id", "job_id"],
            ["jobs.organization_id", "jobs.id"],
            name="job_line_items_job_fkey",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_job_line_items_organization_id"),
        "job_line_items",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        "job_line_items_org_code_idx",
        "job_line_items",
        ["organization_id", "code"],
        unique=False,
        postgresql_where=sa.text("code IS NOT NULL"),
    )
    op.create_index(
        "job_line_items_org_job_idx", "job_line_items", ["organization_id", "job_id"], unique=False
    )
    op.create_table(
        "job_notes",
        sa.Column("job_id", sa.UUID(), nullable=False),
        sa.Column("note_type", sa.Text(), server_default="technician", nullable=False),
        sa.Column("author_name", sa.Text(), nullable=True),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("occurred_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("content_hash", sa.LargeBinary(), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id", "job_id"],
            ["jobs.organization_id", "jobs.id"],
            name="job_notes_job_fkey",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id", "job_id", "content_hash", name="job_notes_org_job_hash_key"
        ),
    )
    op.create_index(
        op.f("ix_job_notes_organization_id"), "job_notes", ["organization_id"], unique=False
    )
    op.create_index(
        "job_notes_org_job_idx", "job_notes", ["organization_id", "job_id"], unique=False
    )
    _seed_plans_and_entitlements()
    for table_name in TENANT_TABLES:
        enable_rls(table_name)
    for table_name in WORKER_TABLES:
        enable_rls_with_worker_access(table_name)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    for table_name in (*reversed(WORKER_TABLES), *reversed(TENANT_TABLES)):
        disable_rls(table_name)
    op.drop_index("job_notes_org_job_idx", table_name="job_notes")
    op.drop_index(op.f("ix_job_notes_organization_id"), table_name="job_notes")
    op.drop_table("job_notes")
    op.drop_index("job_line_items_org_job_idx", table_name="job_line_items")
    op.drop_index(
        "job_line_items_org_code_idx",
        table_name="job_line_items",
        postgresql_where=sa.text("code IS NOT NULL"),
    )
    op.drop_index(op.f("ix_job_line_items_organization_id"), table_name="job_line_items")
    op.drop_table("job_line_items")
    op.drop_index(op.f("ix_import_rows_organization_id"), table_name="import_rows")
    op.drop_index("import_rows_org_batch_idx", table_name="import_rows")
    op.drop_index("import_rows_batch_status_idx", table_name="import_rows")
    op.drop_table("import_rows")
    op.drop_index("jobs_search_document_idx", table_name="jobs", postgresql_using="gin")
    op.drop_index("jobs_org_technician_date_idx", table_name="jobs")
    op.drop_index(
        "jobs_org_source_external_key",
        table_name="jobs",
        postgresql_where=sa.text("external_id IS NOT NULL AND deleted_at IS NULL"),
    )
    op.drop_index(
        "jobs_org_natural_key", table_name="jobs", postgresql_where=sa.text("deleted_at IS NULL")
    )
    op.drop_index(
        "jobs_org_location_date_idx",
        table_name="jobs",
        postgresql_where=sa.text("location_id IS NOT NULL"),
    )
    op.drop_index("jobs_org_last_import_idx", table_name="jobs")
    op.drop_index(
        "jobs_org_equipment_date_idx",
        table_name="jobs",
        postgresql_where=sa.text("equipment_id IS NOT NULL"),
    )
    op.drop_index(
        "jobs_org_embedding_hash_idx",
        table_name="jobs",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index("jobs_org_date_id_idx", table_name="jobs")
    op.drop_index("jobs_org_customer_date_idx", table_name="jobs")
    op.drop_index(op.f("ix_jobs_organization_id"), table_name="jobs")
    op.drop_table("jobs")
    op.drop_index(op.f("ix_equipment_organization_id"), table_name="equipment")
    op.drop_index(
        "equipment_org_serial_idx",
        table_name="equipment",
        postgresql_where=sa.text("serial_number IS NOT NULL"),
    )
    op.drop_index(
        "equipment_org_natural_key",
        table_name="equipment",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index("equipment_org_location_idx", table_name="equipment")
    op.drop_table("equipment")
    op.drop_index("locations_org_postal_code_idx", table_name="locations")
    op.drop_index(
        "locations_org_customer_address_key",
        table_name="locations",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(op.f("ix_locations_organization_id"), table_name="locations")
    op.drop_table("locations")
    op.drop_index(op.f("ix_import_batches_organization_id"), table_name="import_batches")
    op.drop_index(
        "import_batches_org_file_hash_key",
        table_name="import_batches",
        postgresql_where=sa.text(
            "file_sha256 IS NOT NULL AND deleted_at IS NULL AND duplicate_of_batch_id IS NULL"
        ),
    )
    op.drop_index("import_batches_org_created_idx", table_name="import_batches")
    op.drop_index(
        "import_batches_org_active_idx",
        table_name="import_batches",
        postgresql_where=sa.text("status IN ('queued', 'processing')"),
    )
    op.drop_table("import_batches")
    op.drop_index(
        op.f("ix_import_column_mappings_organization_id"), table_name="import_column_mappings"
    )
    op.drop_index("import_column_mappings_org_signature_idx", table_name="import_column_mappings")
    op.drop_table("import_column_mappings")
    op.drop_index(op.f("ix_customers_organization_id"), table_name="customers")
    op.drop_index(
        "customers_org_source_external_key",
        table_name="customers",
        postgresql_where=sa.text("external_id IS NOT NULL AND deleted_at IS NULL"),
    )
    op.drop_index(
        "customers_org_phone_idx",
        table_name="customers",
        postgresql_where=sa.text("phone_e164 IS NOT NULL"),
    )
    op.drop_index("customers_org_normalized_name_idx", table_name="customers")
    op.drop_index(
        "customers_org_natural_key",
        table_name="customers",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_table("customers")
    op.drop_index(op.f("ix_usage_counters_organization_id"), table_name="usage_counters")
    op.drop_table("usage_counters")
    op.drop_index(
        "technicians_org_natural_key",
        table_name="technicians",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(op.f("ix_technicians_organization_id"), table_name="technicians")
    op.drop_table("technicians")
    op.drop_index(op.f("ix_source_systems_organization_id"), table_name="source_systems")
    op.drop_table("source_systems")
    op.drop_index(op.f("ix_service_categories_organization_id"), table_name="service_categories")
    op.drop_table("service_categories")
    op.drop_index(
        op.f("ix_organization_subscriptions_organization_id"),
        table_name="organization_subscriptions",
    )
    op.drop_table("organization_subscriptions")
    op.drop_index(
        op.f("ix_organization_entitlement_overrides_organization_id"),
        table_name="organization_entitlement_overrides",
    )
    op.drop_table("organization_entitlement_overrides")
    op.drop_index(op.f("ix_billing_events_organization_id"), table_name="billing_events")
    op.drop_index("billing_events_org_created_idx", table_name="billing_events")
    op.drop_table("billing_events")
    op.drop_index(op.f("ix_background_jobs_organization_id"), table_name="background_jobs")
    op.drop_index(
        "background_jobs_stale_idx",
        table_name="background_jobs",
        postgresql_where=sa.text("status = 'processing'"),
    )
    op.drop_index("background_jobs_org_type_created_idx", table_name="background_jobs")
    op.drop_index(
        "background_jobs_claim_idx",
        table_name="background_jobs",
        postgresql_where=sa.text("status = 'queued'"),
    )
    op.drop_index(
        "background_jobs_active_idempotency_key",
        table_name="background_jobs",
        postgresql_where=sa.text("idempotency_key IS NOT NULL AND status <> 'failed'"),
    )
    op.drop_table("background_jobs")
    op.drop_index(
        op.f("ix_api_idempotency_records_organization_id"), table_name="api_idempotency_records"
    )
    op.drop_index("api_idempotency_expires_idx", table_name="api_idempotency_records")
    op.drop_table("api_idempotency_records")
    op.drop_table("plan_entitlements")
    op.drop_table("plans")
    for enum_name in (
        "line_item_kind",
        "import_row_status",
        "job_status",
        "import_status",
        "source_system_kind",
        "bg_job_status",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
    # ### end Alembic commands ###
